# Generated by Django 5.2.17 on 2026-08-31 14:32

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My library', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booklife_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.library')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('reading_status', models.CharField(choices=[('interested', 'Interested'), ('queued', 'Queued'), ('reading', 'Reading'), ('read', 'Read'), ('abandoned', 'Abandoned')], default='interested', max_length=16)),
                ('ownership_status', models.CharField(choices=[('wanted', 'To buy'), ('owned', 'Shelf'), ('loaned', 'Loaned'), ('given_away', 'Given away'), ('unknown', 'Unknown')], default='wanted', max_length=16)),
                ('shelf_location', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='catalog.category')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.library')),
            ],
            options={
                'ordering': (django.db.models.functions.text.Lower('title'), 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('discovered', 'Discovered'), ('acquired', 'Acquired'), ('queued', 'Queued'), ('started', 'Started reading'), ('read', 'Read'), ('abandoned', 'Abandoned'), ('loaned', 'Loaned'), ('returned', 'Returned'), ('given_away', 'Given away'), ('restored', 'Restored')], max_length=24)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('happened_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booklife_events', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalog.book')),
            ],
            options={
                'ordering': ('-happened_at', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('library'), name='catalog_category_unique_name_per_library'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['library', 'reading_status'], name='book_library_reading_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['library', 'ownership_status'], name='book_library_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['library', 'finished_on'], name='book_library_finish_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 10)), _connector='OR'), name='catalog_book_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('page_count__isnull', True), models.Q(('page_count__gte', 1), ('page_count__lte', 100000)), _connector='OR'), name='catalog_book_page_count_range'),
        ),
        migrations.AddIndex(
            model_name='lifecycleevent',
            index=models.Index(fields=['book', 'happened_at'], name='event_book_happened_idx'),
        ),
    ]
